import type {
  AutopaySettings,
  BusinessProfile,
  CreditPack,
  PricingPlan,
  SimulationAction,
  UsageRule,
} from '../types';

export const LOW_BALANCE_THRESHOLD = 100;
export const CREDIT_TO_RUPEE_RATIO = 10;

export const pricingPlans: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    amount: 99,
    amountPaise: 9900,
    credits: 990,
    description: 'A focused starter pack for lean teams validating AI-assisted support.',
    idealFor: 'Single-location businesses',
    monthlyCapacity: 'Roughly 198 AI chats or 49 call minutes',
    autopayEligible: true,
  },
  {
    id: 'growth',
    name: 'Growth',
    amount: 199,
    amountPaise: 19900,
    credits: 1990,
    description: 'Balanced usage for growing service teams handling calls, chat, and workflows.',
    idealFor: 'Hotels, clinics, service teams',
    monthlyCapacity: 'Roughly 398 AI chats or 99 call minutes',
    autopayEligible: true,
    highlight: 'Most popular for demos',
  },
  {
    id: 'pro',
    name: 'Pro',
    amount: 499,
    amountPaise: 49900,
    credits: 4990,
    description: 'High-volume automation for multi-agent teams running voice and premium support.',
    idealFor: 'Multi-branch operations',
    monthlyCapacity: 'Roughly 998 AI chats or 249 call minutes',
    autopayEligible: true,
  },
];

export const quickCreditPacks: CreditPack[] = [
  {
    id: 'micro-10',
    label: '10 credits',
    amount: 1,
    amountPaise: 100,
    credits: 10,
    description: 'Tiny recharge for testing a single AI task.',
  },
  {
    id: 'micro-20',
    label: '20 credits',
    amount: 2,
    amountPaise: 200,
    credits: 20,
    description: 'Enough for a short call minute or a few chat requests.',
  },
  {
    id: 'micro-30',
    label: '30 credits',
    amount: 3,
    amountPaise: 300,
    credits: 30,
    description: 'Small top-up for quick support bursts.',
  },
];

export const usageRules: UsageRule[] = [
  {
    id: 'ai_chat',
    label: 'AI Chat',
    credits: 2,
    unit: '/ request',
    description: 'Customer support prompts, FAQ handling, and agent-assist replies.',
    accent: 'mint',
  },
  {
    id: 'sarvam_stt',
    label: 'Sarvam Speech-to-Text',
    credits: 10,
    unit: '/ request',
    description: 'Speech capture, multilingual transcription, and call understanding.',
    accent: 'sky',
  },
  {
    id: 'voice_process',
    label: 'Voice Processing',
    credits: 10,
    unit: '/ action',
    description: 'Intent routing, voice transforms, and response orchestration.',
    accent: 'violet',
  },
  {
    id: 'voice_call',
    label: 'Call Minute',
    credits: 20,
    unit: '/ minute',
    description: 'Standard AI-led call handling with summaries and routing.',
    accent: 'amber',
  },
  {
    id: 'premium_call',
    label: 'Premium AI Call',
    credits: 30,
    unit: '/ minute',
    description: 'Priority handling with advanced triage or concierge flows.',
    accent: 'rose',
  },
  {
    id: 'recording_process',
    label: 'Recording Processing',
    credits: 5,
    unit: '/ file',
    description: 'Post-call transcription, highlights, and QA notes.',
    accent: 'mint',
  },
  {
    id: 'onboarding_ai_setup',
    label: 'Onboarding AI Setup',
    credits: 10,
    unit: '/ action',
    description: 'Business setup generation, workflow tuning, and prompt configuration.',
    accent: 'sky',
  },
];

export const simulationActions: SimulationAction[] = [
  {
    id: 'simulate-ai-chat',
    label: 'Simulate AI Chat',
    description: 'Trigger a support conversation response.',
    credits: 2,
    source: 'ai_chat',
    sourceLabel: 'AI Chat',
    quantityLabel: '1 support exchange',
    referencePrefix: 'CHAT',
    outcome: 'FAQ answered in 4.2s',
  },
  {
    id: 'simulate-sarvam-processing',
    label: 'Simulate Sarvam Processing',
    description: 'Run a speech-to-text or voice transcript job.',
    credits: 10,
    source: 'sarvam_stt',
    sourceLabel: 'Sarvam STT',
    quantityLabel: '1 transcript request',
    referencePrefix: 'SARVAM',
    outcome: 'Transcript generated in Hindi + English',
  },
  {
    id: 'simulate-voice-process',
    label: 'Simulate Voice Process',
    description: 'Process a voice intent and route the next action.',
    credits: 10,
    source: 'voice_process',
    sourceLabel: 'Voice Processing',
    quantityLabel: '1 orchestration cycle',
    referencePrefix: 'VOICE',
    outcome: 'Intent classified and queue assigned',
  },
  {
    id: 'simulate-call-1m',
    label: 'Simulate 1-Minute Call',
    description: 'Show standard call handling with one minute of usage.',
    credits: 20,
    source: 'voice_call',
    sourceLabel: 'Voice Call',
    quantityLabel: '1 minute',
    referencePrefix: 'CALL',
    outcome: 'Reservation inquiry handled end-to-end',
    minutes: 1,
  },
  {
    id: 'simulate-call-5m',
    label: 'Simulate 5-Minute Call',
    description: 'Demonstrate a longer support flow with multiple questions.',
    credits: 100,
    source: 'voice_call',
    sourceLabel: 'Voice Call',
    quantityLabel: '5 minutes',
    referencePrefix: 'CALL',
    outcome: 'Longer support call summarized and tagged',
    minutes: 5,
  },
  {
    id: 'simulate-premium-call',
    label: 'Simulate Premium AI Call',
    description: 'Premium concierge or escalation-grade call routing.',
    credits: 30,
    source: 'premium_call',
    sourceLabel: 'Premium AI Call',
    quantityLabel: '1 minute premium',
    referencePrefix: 'PREM',
    outcome: 'VIP escalation completed with premium workflow',
    minutes: 1,
  },
  {
    id: 'simulate-recording-processing',
    label: 'Simulate Recording Processing',
    description: 'Process an uploaded or post-call recording.',
    credits: 5,
    source: 'recording_process',
    sourceLabel: 'Recording Processing',
    quantityLabel: '1 recording',
    referencePrefix: 'REC',
    outcome: 'Recording summary + QA highlights generated',
  },
  {
    id: 'simulate-onboarding-setup',
    label: 'Simulate Onboarding Setup',
    description: 'Generate onboarding prompts, flows, or configuration.',
    credits: 10,
    source: 'onboarding_ai_setup',
    sourceLabel: 'Onboarding AI Setup',
    quantityLabel: '1 setup action',
    referencePrefix: 'SETUP',
    outcome: 'Business profile and assistant rules refreshed',
  },
];

export const defaultAutopaySettings: AutopaySettings = {
  enabled: true,
  selectedPlanId: 'growth',
  triggerType: 'low_balance',
  thresholdCredits: LOW_BALANCE_THRESHOLD,
  rechargeAmount: pricingPlans[1].amountPaise,
  mode: 'demo',
  preferredPaymentMethod: 'upi',
  upiId: '',
  paymentMethodLabel: 'Customer-approved Razorpay checkout',
  status: 'active',
  lastAutopayAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
  nextAutopayAttemptAt: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
  pendingCheckout: null,
};

export const defaultBusinessProfile: BusinessProfile = {
  businessName: 'Versafic Demo Operations',
  businessType: 'AI Customer Support Platform',
  industry: 'Hospitality & Services',
  website: 'https://versafic.com',
  country: 'India',
  phone: '+91 98765 43210',
  supportWorkflowStatus: 'Voice + chat flows active',
  aiSetupStatus: 'Knowledge base synced 2 hours ago',
  onboardingStage: 'Live demo ready',
  lastSyncAt: new Date().toISOString(),
};

export const getPlanById = (planId: string): PricingPlan =>
  pricingPlans.find((plan) => plan.id === planId) ?? pricingPlans[1];
